# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sie',
                'doc_host': 'https://bblais.github.io',
                'git_url': 'https://github.com/bblais/sie',
                'lib_path': 'sie'},
  'syms': {'sie.core': {'sie.core.foo': ('core.html#foo', 'sie/core.py')}}}
