# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_core.ipynb.

# %% auto 0
__all__ = ['size', 'family']

# %% ../notebooks/00_core.ipynb 2
import matplotlib as mpl
mpl.rcParams['lines.linewidth'] = 3
mpl.rcParams['figure.figsize'] = (12,8)
mpl.rcParams['axes.grid']=True

size=20
family='sans-serif'


from matplotlib import rc
rc('font',size=size,family=family)
rc('axes',labelsize=size)
rc('axes',titlesize=size)
rc('xtick',labelsize=size)
rc('ytick',labelsize=size)
rc('legend',fontsize=size)

